//
//  Occurrence.swift
//  CalendarCore
//

import Foundation

/// An event that may repeat, by a ChronoKit ``RecurrenceRule``. Expand a
/// list of them with ``Timetable/expand(_:in:calendar:)`` before handing
/// them to a view.
///
/// Read a rule from iCalendar text or from words — `try RecurrenceRule(parsing:
/// "FREQ=MONTHLY;BYDAY=-1FR")` or `"the last friday of every month"` — and
/// write it back with `rruleString`.
public protocol RecurringEvent: CalendarEvent {

    /// How the event repeats, or `nil` for a one-off.
    var recurrence: RecurrenceRule? { get }
}

/// One occurrence of a ``RecurringEvent``: the event, moved to when this
/// occurrence happens. A one-off event expands to a single occurrence of itself.
public struct Occurrence<Event: RecurringEvent>: CalendarEvent {

    /// The event this is an occurrence of.
    public let event: Event

    /// When this occurrence starts.
    public let start: Date

    /// When it ends.
    public let end: Date

    /// Identifies the occurrence: the event and its start.
    public struct ID: Hashable {
        public let event: Event.ID
        public let start: Date
    }

    public var id: ID { ID(event: event.id, start: start) }

    public var isAllDay: Bool { event.isAllDay }

    /// The rule it was generated by, if the event repeats.
    public var recurrence: RecurrenceRule? { event.recurrence }
}

extension Occurrence: Sendable where Event: Sendable, Event.ID: Sendable {}
extension Occurrence.ID: Sendable where Event.ID: Sendable {}
extension Occurrence: Equatable where Event: Equatable {
    public static func == (a: Occurrence, b: Occurrence) -> Bool { a.event == b.event && a.start == b.start && a.end == b.end }
}

extension CalendarEvent {

    /// By default, whether this is a ``RecurringEvent`` (or an ``Occurrence``
    /// of one) that actually repeats.
    public var isRecurring: Bool {
        (self as? any RecurringEvent)?.recurrence != nil
    }
}

extension RecurrenceRule {

    /// The rule in words, with what it leaves to the first occurrence filled
    /// in: "every Monday" rather than "every week", "the 4th of every month"
    /// rather than "every month". In the calendar's language for Spanish,
    /// French, German, Italian, Portuguese, Dutch, Japanese, Korean, Chinese,
    /// Russian and Arabic, for the common shapes; otherwise ChronoKit's English.
    ///
    /// - Parameter start: the series' first occurrence.
    public func phrase(from start: Date, calendar: Calendar = .current) -> String {
        Phrasing.describe(self, from: start, calendar: calendar)
    }
}
