//
//  CalendarEvent+Recurring.swift
//  CalendarCore
//

import Foundation

extension CalendarEvent {

    /// By default, whether this is a ``RecurringEvent`` (or an ``Occurrence``
    /// of one) that actually repeats.
    public var isRecurring: Bool {
        (self as? any RecurringEvent)?.recurrence != nil
    }
}

extension Occurrence {

    /// The rule it was generated by, if the event repeats.
    public var recurrence: RecurrenceRule? { event.recurrence }
}
